Our project aims to predict the median house value of houses in California. We are using the dataset from here: https://www.kaggle.com/datasets/abdallahsamman/california-housing-with-name-of-counties/

In [5]:
# Standard Headers
import pandas as pd
import matplotlib.pyplot as plt

# Enable inline mode for matplotlib so that Jupyter displays graphs
%matplotlib inline

In [7]:
# Initial data
data = pd.read_csv('California_Housing_CitiesAdded.csv', header='infer')
data.head()
data

,Median_House_Value,Median_Income,Median_Age,Tot_Rooms,Tot_Bedrooms,Population,Households,Latitude,Longitude,Distance_to_coast,Distance_to_LA,Distance_to_SanDiego,Distance_to_SanJose,Distance_to_SanFrancisco,ocean_proximity,City
0,500001.0,1.2434,52,249,78,396,85,37.80,-122.27,2524.614616,552234.05150,7.310236e+05,61415.35211,14466.70538,NEAR BAY,Alameda
1,500001.0,1.1696,52,609,236,1349,250,37.87,-122.25,7897.024567,556856.92800,7.357884e+05,67242.51828,19172.81885,NEAR BAY,Alameda
2,500001.0,7.8521,52,1668,225,517,214,37.86,-122.24,9154.528309,555442.50860,7.343726e+05,65849.13943,19335.74118,NEAR BAY,Alameda
3,500001.0,9.3959,52,3726,474,1366,496,37.85,-122.24,8259.085109,554610.71710,7.335257e+05,64867.28983,18811.48745,NEAR BAY,Alameda
4,500001.0,7.8772,52,2990,379,947,361,37.83,-122.23,7284.913015,552365.47120,7.312636e+05,62493.11252,18750.94628,NEAR BAY,Alameda
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20635,17500.0,2.3667,39,493,168,259,138,34.15,-118.33,21926.839290,13466.35773,1.928705e+05,478320.29920,546350.05960,<1H OCEAN,Los Angeles
20636,14999.0,1.6607,16,255,73,85,38,39.71,-122.74,89894.935430,745210.34300,9.243866e+05,274118.58350,216934.52110,INLAND,Glenn
20637,14999.0,2.1000,19,619,239,490,164,36.40,-117.02,297347.746600,283729.02440,4.098750e+05,445744.27790,503631.71850,INLAND,Kern
20638,14999.0,4.1932,52,803,267,628,225,34.24,-117.86,61064.660150,41019.72423,1.814618e+05,500708.74560,568617.45930,INLAND,Los Angeles
20639,14999.0,0.5360,36,98,28,18,8,40.31,-123.17,78672.517530,821033.80620,1.000130e+06,348749.47090,289116.49840,INLAND,Shasta

In [ ]:
# Data cleaning, feature selection, feature engineering

In [ ]:
# Train model on data using sklearn
# (What do we want to use? Neural net, random forest, AdaBoost, SVM, etc?)
# Hyperparameter tuning

In [ ]:
# Test the model and evaluate the accuracy (maybe also other metrics, like precision/recall)